const { defineConfig } = require('cz-git');

module.exports = defineConfig({
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'revert',
        'build',
        'ci',
      ],
    ],
    'scope-case': [0, 'always'],
  },
  prompt: {
    alias: { fd: 'docs: fix documentation' },
    messages: {
      type: '选择你要提交的类型:',
      scope: '选择或输入修改范围(可选):',
      customScope: '请输入修改范围:',
      subject: '简短描述修改内容:\n',
      body: '详细描述修改内容(可选)，使用 "|" 换行:\n',
      breaking: '列举非兼容性重大破坏(可选):\n',
      footerPrefixsSelect: '选择关联issue前缀(可选):',
      customFooterPrefixs: '输入自定义issue前缀:',
      footer: '关联issue 例如: #123, 多个使用空格分隔:\n',
      confirmCommit: '当前提交信息是否正确?',
    },
    types: [
      { value: 'feat', name: 'feat:     新增功能', emoji: '✨' },
      { value: 'fix', name: 'fix:      修复 bug', emoji: '🐛' },
      { value: 'docs', name: 'docs:      文档更新', emoji: '📝' },
      { value: 'style', name: 'style:     代码格式调整', emoji: '💄' },
      { value: 'refactor', name: 'refactor: 重构', emoji: '♻️' },
      { value: 'perf', name: 'perf:      性能优化', emoji: '⚡️' },
      { value: 'test', name: 'test:      测试相关', emoji: '✅' },
      { value: 'chore', name: 'chore:     构建/工具相关', emoji: '🔧' },
      { value: 'revert', name: 'revert:    回滚提交', emoji: '⏪' },
      { value: 'build', name: 'build:     构建系统变更', emoji: '🏗️' },
      { value: 'ci', name: 'ci:        CI/CD 相关', emoji: '👷' },
    ],
    useEmoji: true,
    emojiAlign: 'left',
    scopesSearchValue: '',
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    emptyScopesAlias: 'empty',
    customScopesAlias: 'custom',
    breakingLevelChangeAlign: 'top',
    allowBreakingChanges: ['feat', 'fix'],
    breakingLevelChangeAlias: ['BREAKING CHANGE'],
  },
});
